version: '3'
services:

  db:
    image: mysql:8.0
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h ${DB_HOST} -u ${DB_USER} -p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    expose:
      - ${DB_PORT}

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "${PORT}:${PORT}"
    environment:
      PUBLIC_HOST: ${PUBLIC_HOST}
      PORT: ${PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

volumes:
  db_data:
